package com.barcodereader.util

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.widget.Toast
import android.graphics.Bitmap
import android.provider.MediaStore
import java.io.OutputStream
import java.io.File
import java.io.FileOutputStream

object FormatUtils {

    fun detectType(content: String): String {
        return when {
            content.startsWith("http://") || content.startsWith("https://") -> "URL"
            content.matches(Regex("^[\\w.+-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) -> "EMAIL"
            content.matches(Regex("^\\+?[1-9]\\d{6,14}$")) -> "PHONE"
            content.matches(Regex("^[A-Z0-9]{6,}$")) -> "COUPON"
            content.matches(Regex("^\\d{12,13}$")) -> "PRODUCT"
            content.matches(Regex("^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$")) && content.length > 20 -> "BASE64"
            content.matches(Regex("^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$")) -> "BITCOIN"
            content.matches(Regex("^0x[a-fA-F0-9]{40}$")) -> "ETHEREUM"
            content.matches(Regex("^WIFI:[Tt]:[^;]+;[Ss]:[^;]+;.*")) -> "WIFI"
            content.matches(Regex("^BEGIN:VCARD", RegexOption.IGNORE_CASE)) -> "VCARD"
            content.matches(Regex("^BEGIN:VCALENDAR", RegexOption.IGNORE_CASE)) -> "VCALENDAR"
            content.matches(Regex("^geo:-?\\d+\\.\\d+,-?\\d+\\.\\d+.*")) -> "LOCATION"
            content.matches(Regex("^sms:[\\w.+\\-@]+.*")) -> "SMS"
            content.matches(Regex("^market://.*|^https://play\\.google\\.com/.*")) -> "PLAY_STORE"
            else -> "TEXT"
        }
    }

    fun copyToClipboard(context: Context, text: String) {
        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        val clip = ClipData.newPlainText("barcode", text)
        clipboard.setPrimaryClip(clip)
        Toast.makeText(context, "Copied to clipboard", Toast.LENGTH_SHORT).show()
    }

    fun shareText(context: Context, text: String) {
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
        }
        context.startActivity(Intent.createChooser(intent, "Share via"))
    }

    fun openInBrowser(context: Context, url: String) {
        val intent = Intent(Intent.ACTION_VIEW, android.net.Uri.parse(url))
        context.startActivity(intent)
    }

    fun formatTimestamp(timestamp: Long): String {
        val now = System.currentTimeMillis()
        val diff = now - timestamp
        val seconds = diff / 1000
        val minutes = seconds / 60
        val hours = minutes / 60
        val days = hours / 24

        return when {
            seconds < 60 -> "Just now"
            minutes < 60 -> "${minutes}m ago"
            hours < 24 -> "${hours}h ago"
            days < 7 -> "${days}d ago"
            else -> {
                val sdf = java.text.SimpleDateFormat("MMM dd", java.util.Locale.getDefault())
                sdf.format(java.util.Date(timestamp))
            }
        }
    }

    /**
     * Shares a bitmap image via Android share sheet.
     * The bitmap is written to the app's cache directory and shared as a content URI.
     */
    fun shareImage(context: Context, bitmap: Bitmap) {
        try {
            // Write bitmap to a temporary file in cache directory
            val cachePath = File(context.cacheDir, "images")
            cachePath.mkdirs()
            val file = File(cachePath, "shared_image_${System.currentTimeMillis()}.png")
            val stream: OutputStream = FileOutputStream(file)
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream)
            stream.flush()
            stream.close()

            // Get URI using FileProvider (fallback to MediaStore if not set up)
            val uri = androidx.core.content.FileProvider.getUriForFile(
                context,
                context.packageName + ".fileprovider",
                file
            )
            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "image/*"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(Intent.createChooser(shareIntent, "Share Image"))
        } catch (e: Exception) {
            Toast.makeText(context, "Failed to share image: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    /**
     * Saves a bitmap image to the device's gallery.
     */
    fun saveImageToGallery(context: Context, bitmap: Bitmap) {
        try {
            MediaStore.Images.Media.insertImage(
                context.contentResolver,
                bitmap,
                "barcode_${System.currentTimeMillis()}",
                "Generated by Barcode Reader"
            )
            Toast.makeText(context, "Image saved to gallery", Toast.LENGTH_SHORT).show()
        } catch (e: Exception) {
            Toast.makeText(context, "Failed to save image: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }
}